#include "terrain_format.h"
#include "terrain_generator.h"
#include "terrain_preview.h"
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>
#include <raylib.h>
#include <raymath.h>
#include <tinyfiledialogs.h>
namespace {
  constexpr int window_width = 674, window_height = 515, panel_x = 482, titlebar_height = 30, frame_width = 8;
  Font ui_font{};
  void ui_text(const char* text, int x, int y, int size, Color color) { DrawTextEx(ui_font, text, Vector2{static_cast<float>(x),static_cast<float>(y)}, static_cast<float>(size), 1, color); }
  int ui_measure(const char* text, int size) { return static_cast<int>(MeasureTextEx(ui_font,text,static_cast<float>(size),1).x); }
#define DrawText ui_text
#define MeasureText ui_measure
  Vector2 ui_mouse_position() { auto point=GetMousePosition(); point.x+=frame_width; point.y+=titlebar_height; return point; }
#if defined(_WIN32)
  using NativeHandle = void*;
  extern "C" __declspec(dllimport) NativeHandle __stdcall GetModuleHandleW(const wchar_t*);
  extern "C" __declspec(dllimport) NativeHandle __stdcall GetActiveWindow();
  extern "C" __declspec(dllimport) NativeHandle __stdcall LoadImageW(NativeHandle,const wchar_t*,unsigned,int,int,unsigned);
  extern "C" __declspec(dllimport) std::intptr_t __stdcall SendMessageW(NativeHandle,unsigned,std::uintptr_t,std::intptr_t);
  void set_window_icon() { const auto resource=reinterpret_cast<const wchar_t*>(static_cast<std::uintptr_t>(101)); const auto icon=LoadImageW(GetModuleHandleW(nullptr),resource,1,0,0,0x40); const auto window=GetActiveWindow(); if(icon&&window){SendMessageW(window,0x0080,0,reinterpret_cast<std::intptr_t>(icon));SendMessageW(window,0x0080,1,reinterpret_cast<std::intptr_t>(icon));} }
#endif
  struct State { terrain::TerrainMapDocument document{.width=32,.height=32,.generated="terrain_bf-32.nw",.map_seed=0,.base_height=0,.even_borders=false,.map_height=65,.map_chaos=.6,.level_height=5.0544,.level_chaos=.6}; std::vector<terrain::PreviewColor> pixels; bool random=true, grid=true, details=false, graal_levels=false,dragging=false; int zoom_x{},zoom_y{},active=-1,drag_x{},drag_y{},drag_mouse_y{},selected_x=-1,selected_y=-1; double vertex_height{}; float zoom=1; std::string input; } state;
  Rectangle box(float x, float y, float width, float height) { return {x,y,width,height}; }
  bool button(const char* text, Rectangle area) { DrawRectangleRec(area, Color{236,236,236,255}); DrawRectangleLinesEx(area, 1, GRAY); const int w=MeasureText(text,12); DrawText(text,static_cast<int>(area.x+(area.width-w)/2),static_cast<int>(area.y+5),12,BLACK); return CheckCollisionPointRec(ui_mouse_position(),area)&&IsMouseButtonReleased(MOUSE_BUTTON_LEFT); }
  bool icon_button(int icon, Rectangle area) { DrawRectangleRec(area,Color{236,236,236,255}); DrawRectangleLinesEx(area,1,GRAY); if(icon==0){DrawRectangle(static_cast<int>(area.x+4),static_cast<int>(area.y+9),13,7,GOLD);DrawRectangle(static_cast<int>(area.x+5),static_cast<int>(area.y+6),7,4,GOLD);DrawRectangleLines(static_cast<int>(area.x+4),static_cast<int>(area.y+9),13,7,BLACK);} else {DrawRectangle(static_cast<int>(area.x+5),static_cast<int>(area.y+4),12,13,Color{30,30,30,255});DrawRectangle(static_cast<int>(area.x+7),static_cast<int>(area.y+5),7,4,SKYBLUE);DrawRectangle(static_cast<int>(area.x+7),static_cast<int>(area.y+12),7,4,RAYWHITE);} return CheckCollisionPointRec(ui_mouse_position(),area)&&IsMouseButtonReleased(MOUSE_BUTTON_LEFT); }
  void check(const char* text, float x, float y, bool& value) { Rectangle area=box(x,y,13,13); DrawRectangleRec(area,RAYWHITE); DrawRectangleLinesEx(area,1,GRAY); if(value) DrawText("x",static_cast<int>(x+2),static_cast<int>(y-1),14,BLACK); DrawText(text,static_cast<int>(x+18),static_cast<int>(y),12,BLACK); if(CheckCollisionPointRec(ui_mouse_position(),box(x,y,150,16))&&IsMouseButtonReleased(MOUSE_BUTTON_LEFT)) value=!value; }
  void field(int id,const char* label, float x, float y, const std::string& value) { DrawText(label,static_cast<int>(x),static_cast<int>(y+4),12,BLACK); const Rectangle area=box(x+96,y,64,20); DrawRectangleRec(area,RAYWHITE); DrawRectangleLinesEx(area,1,state.active==id?BLACK:GRAY); const auto& text=state.active==id?state.input:value; DrawText(text.c_str(),static_cast<int>(x+99),static_cast<int>(y+4),12,BLACK); if(CheckCollisionPointRec(ui_mouse_position(),area)&&IsMouseButtonReleased(MOUSE_BUTTON_LEFT)){state.active=id;state.input=value;} }
  std::string number(double value) { char result[32]; std::snprintf(result,sizeof(result),"%g",value); return result; }
  void spin_field(int id,const char* label,float x,float y,double& value,double step) { DrawText(label,static_cast<int>(x),static_cast<int>(y+4),12,BLACK); const Rectangle area=box(x+96,y,64,20),arrows=box(area.x+48,area.y,16,20); DrawRectangleRec(area,RAYWHITE); DrawRectangleLinesEx(area,1,state.active==id?BLACK:GRAY); DrawLine(static_cast<int>(arrows.x),static_cast<int>(arrows.y+10),static_cast<int>(arrows.x+16),static_cast<int>(arrows.y+10),GRAY); DrawTriangle(Vector2{arrows.x+8,arrows.y+3},Vector2{arrows.x+4,arrows.y+8},Vector2{arrows.x+12,arrows.y+8},BLACK); DrawTriangle(Vector2{arrows.x+4,arrows.y+12},Vector2{arrows.x+12,arrows.y+12},Vector2{arrows.x+8,arrows.y+17},BLACK); const auto text=state.active==id?state.input:number(value); DrawText(text.c_str(),static_cast<int>(area.x+3),static_cast<int>(area.y+4),12,BLACK); if(CheckCollisionPointRec(ui_mouse_position(),arrows)&&IsMouseButtonReleased(MOUSE_BUTTON_LEFT)){value+=ui_mouse_position().y<arrows.y+10?step:-step;state.active=-1;} else if(CheckCollisionPointRec(ui_mouse_position(),box(area.x,area.y,48,20))&&IsMouseButtonReleased(MOUSE_BUTTON_LEFT)){state.active=id;state.input=number(value);} }
  void rebuild(bool generate=false) { if(generate) terrain::regenerate_terrain_map(state.document); state.pixels.assign(static_cast<size_t>(state.document.width)*state.document.height,{}); const int width=state.document.width; for(int y=0;y<state.document.height;++y) for(int x=0;x<state.document.width;++x) { const auto control=[&](int control_x,int control_y){return state.document.heightmap[control_y*(width+1)+control_x];}; state.pixels[y*width+x]=terrain::preview_color(control(x,y),control(x+1,y),control(x,y+1),control(x+1,y+1),true); } }
  std::string current_map_path;
  void open_document() { const char* patterns[]{"*.gmap"}; const char* selected=tinyfd_openFileDialog("Open terrain map",current_map_path.empty()?nullptr:current_map_path.c_str(),1,patterns,"Graal map",0); if(!selected)return; std::ifstream input(selected,std::ios::binary); if(!input)return; state.document=terrain::parse_terrain_gmap(std::string{std::istreambuf_iterator<char>{input},{}}); current_map_path=selected; state.selected_x=state.selected_y=-1; state.vertex_height=0; rebuild(); }
  void save_generated_levels(const std::filesystem::path& map_path) { const std::array<double,81> empty{}; for(int y=0;y<state.document.height;++y)for(int x=0;x<state.document.width;++x){const auto name=terrain::generated_level_name(state.document,x,y); if(name.empty())continue; const auto override=std::find_if(state.document.height_overrides.begin(),state.document.height_overrides.end(),[&](const auto& item){return item.level_name==name;}); std::ofstream output(map_path.parent_path()/name,std::ios::binary|std::ios::trunc); if(output)output<<terrain::serialize_terrain_level(override==state.document.height_overrides.end()?std::span<const double,81>{empty}:std::span<const double,81>{override->samples},override!=state.document.height_overrides.end());} }
  void save_document(bool choose_path) { const char* patterns[]{"*.gmap"}; const char* selected=choose_path||current_map_path.empty()?tinyfd_saveFileDialog("Save terrain map",current_map_path.empty()?"terrain.gmap":current_map_path.c_str(),1,patterns,"Graal map"):current_map_path.c_str(); if(!selected)return; const std::filesystem::path map_path(selected); std::ofstream output(map_path,std::ios::binary|std::ios::trunc); if(!output)return; output<<terrain::serialize_terrain_gmap(state.document); output.close(); if(state.graal_levels)save_generated_levels(map_path); current_map_path=selected; }
  void commit_input() { try { switch(state.active){case 0:state.document.map_seed=static_cast<uint32_t>(std::stoul(state.input));break;case 1:state.document.width=std::clamp(std::stoi(state.input),1,64);break;case 2:state.document.height=std::clamp(std::stoi(state.input),1,64);break;case 3:state.document.base_height=std::stod(state.input);break;case 4:state.document.map_height=std::stod(state.input);break;case 5:state.document.map_chaos=std::stod(state.input);break;case 6:state.vertex_height=std::stod(state.input);if(state.selected_x>=0){terrain::edit_control_height(state.document,state.selected_x,state.selected_y,state.vertex_height);rebuild();}break;} }catch(...){} state.active=-1; }
}
int terrain_cli_main(int argument_count, char** arguments);
int terrain_self_test();
int main(int argument_count, char** arguments) {
  if (argument_count == 2 && std::string_view(arguments[1]) == "--self-test") return terrain_self_test();
  if (argument_count > 1) return terrain_cli_main(argument_count, arguments);
  SetConfigFlags(FLAG_WINDOW_RESIZABLE); InitWindow(window_width,window_height,"Terrain Generator");
#if defined(_WIN32)
  set_window_icon();
#endif
  const std::array<const char*,3> font_paths{"C:/Windows/Fonts/tahoma.ttf","/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf","/System/Library/Fonts/Supplemental/Arial.ttf"}; for(const auto path:font_paths) if(std::filesystem::exists(path)){ui_font=LoadFontEx(path,12,nullptr,0);break;} if(!ui_font.texture.id) ui_font=GetFontDefault(); SetTextureFilter(ui_font.texture,TEXTURE_FILTER_BILINEAR); SetTargetFPS(60); rebuild(true);
  while(!WindowShouldClose()) { if(state.active>=0){int key;while((key=GetCharPressed())>0)if((key>='0'&&key<='9')||key=='.'||key=='-')state.input+=static_cast<char>(key);if(IsKeyPressed(KEY_BACKSPACE)&&!state.input.empty())state.input.pop_back();if(IsKeyPressed(KEY_ENTER))commit_input();} BeginDrawing(); ClearBackground(RAYWHITE); BeginMode2D(Camera2D{{0,0},{static_cast<float>(frame_width),static_cast<float>(titlebar_height)},0,1}); DrawRectangle(panel_x,titlebar_height,GetScreenWidth()-panel_x+frame_width,GetScreenHeight(),Color{238,238,238,255}); DrawText("Random Seed:",498,49,12,BLACK); field(0,"",489,43,std::to_string(state.document.map_seed)); check("random",585,68,state.random);
    DrawRectangleLinesEx(box(489,100,191,218),1,GRAY); DrawText("Generator Options",499,98,12,BLACK); field(1,"Grid width:",505,116,std::to_string(state.document.width)); field(2,"Grid height:",505,139,std::to_string(state.document.height)); spin_field(3,"Base:",505,171,state.document.base_height,1); check("Even borders",505,197,state.document.even_borders); field(4,"Height:",505,216,number(state.document.map_height)); field(5,"Chaos:",505,239,number(state.document.map_chaos)); DrawText("Presets:",505,270,12,BLACK); if(button("Standard",box(569,264,99,23))){state.document.base_height=0;state.document.even_borders=false;state.document.map_height=65;state.document.map_chaos=.6;} if(button("Islands",box(569,288,99,23))){state.document.base_height=-32;state.document.even_borders=true;}
    if(button("Generate World",box(521,328,131,23))){if(state.active>=0)commit_input();if(state.random) state.document.map_seed=static_cast<uint32_t>(std::chrono::high_resolution_clock::now().time_since_epoch().count()); rebuild(true);} check("Show grid",498,361,state.grid); check("Show level details",498,378,state.details); const double previous_vertex_height=state.vertex_height; spin_field(6,"Vertex height:",498,394,state.vertex_height,1); if(state.selected_x>=0&&state.vertex_height!=previous_vertex_height){terrain::edit_control_height(state.document,state.selected_x,state.selected_y,state.vertex_height);rebuild();} if(button("Zoom in/out",box(498,426,88,24))) state.zoom=state.zoom==1?1.5f:1; DrawText("Move zoom:",604,431,12,BLACK); if(button("^",box(622,445,22,22)))--state.zoom_y; if(button("<",box(599,461,22,22)))--state.zoom_x; if(button(">",box(645,461,22,22)))++state.zoom_x; if(button("v",box(622,477,22,18)))++state.zoom_y; if(icon_button(0,box(506,472,21,21)))open_document(); if(icon_button(1,box(531,472,21,21)))save_document(false); if(icon_button(1,box(555,472,21,21)))save_document(true); DrawRectangleLinesEx(box(489,508,191,43),1,GRAY); DrawText("Save Options",499,506,12,BLACK); check("Generate Graal levels",505,525,state.graal_levels);
    if(CheckCollisionPointRec(ui_mouse_position(),box(21,70,440,440)) && IsMouseButtonPressed(MOUSE_BUTTON_LEFT)) { const auto mouse=ui_mouse_position(); const float scale=14*state.zoom; state.drag_x=(std::clamp)(static_cast<int>((mouse.x-21-state.zoom_x*8)/scale+.5f),0,state.document.width); state.drag_y=(std::clamp)(static_cast<int>((mouse.y-70-state.zoom_y*8)/scale+.5f),0,state.document.height); state.selected_x=state.drag_x;state.selected_y=state.drag_y;state.vertex_height=state.document.heightmap[state.drag_y*(state.document.width+1)+state.drag_x]; state.drag_mouse_y=GetMouseY(); state.dragging=true; }
    if(state.dragging && IsMouseButtonDown(MOUSE_BUTTON_LEFT)) { const int delta=state.drag_mouse_y-GetMouseY(); if(delta){const auto index=state.drag_y*(state.document.width+1)+state.drag_x; terrain::edit_control_height(state.document,state.drag_x,state.drag_y,state.document.heightmap[index]+delta*.5); state.vertex_height=state.document.heightmap[index]; state.drag_mouse_y=GetMouseY(); rebuild();} }
    if(IsMouseButtonReleased(MOUSE_BUTTON_LEFT)) state.dragging=false;
    if(!state.pixels.empty()){const int pw=state.document.width,ph=state.document.height; const float scale=14*state.zoom,ox=21+state.zoom_x*8,oy=70+state.zoom_y*8; const auto point=[&](int x,int y){return Vector2{ox+x*scale,oy+y*scale-static_cast<float>(state.document.heightmap[y*(pw+1)+x])*.35f};}; BeginScissorMode(13,40,440,440); for(int y=0;y<ph;++y)for(int x=0;x<pw;++x){const auto c=state.pixels[y*pw+x]; const auto tl=point(x,y),tr=point(x+1,y),bl=point(x,y+1),br=point(x+1,y+1); DrawTriangle(tl,bl,br,Color{c.red,c.green,c.blue,255});DrawTriangle(tl,br,tr,Color{c.red,c.green,c.blue,255});if(state.grid){DrawLineV(tl,tr,BLACK);DrawLineV(tl,bl,BLACK);DrawLineV(bl,br,BLACK);DrawLineV(tr,br,BLACK);}if(state.details){for(int sy=1;sy<8;++sy){const float t=sy/8.0f;DrawLineV(Vector2Lerp(tl,bl,t),Vector2Lerp(tr,br,t),Color{0,0,0,100});DrawLineV(Vector2Lerp(tl,tr,t),Vector2Lerp(bl,br,t),Color{0,0,0,100});}}} EndScissorMode();}
    EndMode2D(); EndDrawing(); } CloseWindow(); }
