#include "terrain_format.h"
#include "terrain_generator.h"
#include "terrain_preview.h"
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>
#include <raylib.h>
#include <raymath.h>
#include <tinyfiledialogs.h>
namespace {
  constexpr int window_width = 688, window_height = 522, panel_x = 482, titlebar_height = 30, frame_width = 0;
  constexpr int terrain_left = 20, terrain_top = 70, terrain_width = 442, terrain_height = 440;
  Font ui_font{};
  void ui_text(const char* text, int x, int y, int size, Color color) { DrawTextEx(ui_font, text, Vector2{static_cast<float>(x),static_cast<float>(y)}, static_cast<float>(size), 1, color); }
  int ui_measure(const char* text, int size) { return static_cast<int>(MeasureTextEx(ui_font,text,static_cast<float>(size),1).x); }
#define DrawText ui_text
#define MeasureText ui_measure
  Vector2 ui_mouse_position() { auto point=GetMousePosition(); point.y+=titlebar_height; return point; }
#if defined(_WIN32)
  using NativeHandle = void*;
  extern "C" __declspec(dllimport) NativeHandle __stdcall GetModuleHandleW(const wchar_t*);
  extern "C" __declspec(dllimport) NativeHandle __stdcall GetActiveWindow();
  extern "C" __declspec(dllimport) NativeHandle __stdcall LoadImageW(NativeHandle,const wchar_t*,unsigned,int,int,unsigned);
  extern "C" __declspec(dllimport) std::intptr_t __stdcall SendMessageW(NativeHandle,unsigned,std::uintptr_t,std::intptr_t);
  void set_window_icon() { const auto resource=reinterpret_cast<const wchar_t*>(static_cast<std::uintptr_t>(101)); const auto icon=LoadImageW(GetModuleHandleW(nullptr),resource,1,0,0,0x40); const auto window=GetActiveWindow(); if(icon&&window){SendMessageW(window,0x0080,0,reinterpret_cast<std::intptr_t>(icon));SendMessageW(window,0x0080,1,reinterpret_cast<std::intptr_t>(icon));} }
#endif
  struct State { terrain::TerrainMapDocument document{.width=32,.height=32,.generated="terrain_bf-32.nw",.map_seed=0,.base_height=0,.even_borders=false,.map_height=65,.map_chaos=.6,.level_height=5.0544,.level_chaos=.6}; std::vector<terrain::PreviewColor> pixels,detail_pixels; std::vector<double> detail_heights,zoom_heights; bool random=true, grid=true, details=false, graal_levels=false,dragging=false,input_selected=false,selected_detail=false; int zoom_x{},zoom_y{},active=-1,drag_x{},drag_y{},drag_mouse_y{},selected_x=-1,selected_y=-1,detail_level_x=-1,detail_level_y=-1,detail_sample_x=-1,detail_sample_y=-1; double vertex_height{}; float zoom=1; std::size_t input_cursor{}; std::string input; } state;
  Rectangle box(float x, float y, float width, float height) { return {x,y,width,height}; }
  bool button_frame(Rectangle area) { const bool hover=CheckCollisionPointRec(ui_mouse_position(),area),pressed=hover&&IsMouseButtonDown(MOUSE_BUTTON_LEFT); DrawRectangleRec(area,Color{236,236,236,255}); const Color top=pressed?Color{80,80,80,255}:RAYWHITE,bottom=pressed?RAYWHITE:Color{80,80,80,255}; DrawLine(static_cast<int>(area.x),static_cast<int>(area.y),static_cast<int>(area.x+area.width-1),static_cast<int>(area.y),top); DrawLine(static_cast<int>(area.x),static_cast<int>(area.y),static_cast<int>(area.x),static_cast<int>(area.y+area.height-1),top); DrawLine(static_cast<int>(area.x),static_cast<int>(area.y+area.height-1),static_cast<int>(area.x+area.width-1),static_cast<int>(area.y+area.height-1),bottom); DrawLine(static_cast<int>(area.x+area.width-1),static_cast<int>(area.y),static_cast<int>(area.x+area.width-1),static_cast<int>(area.y+area.height-1),bottom); return pressed; }
  bool button(const char* text, Rectangle area) { const bool pressed=button_frame(area); const int w=MeasureText(text,12),offset=pressed?1:0; DrawText(text,static_cast<int>(area.x+(area.width-w)/2)+offset,static_cast<int>(area.y+5)+offset,12,BLACK); return pressed&&IsMouseButtonPressed(MOUSE_BUTTON_LEFT); }
  void disabled_button(const char* text, Rectangle area) { DrawRectangleRec(area,Color{236,236,236,255}); DrawRectangleLinesEx(area,1,LIGHTGRAY); const int w=MeasureText(text,12); DrawText(text,static_cast<int>(area.x+(area.width-w)/2),static_cast<int>(area.y+5),12,LIGHTGRAY); }
  bool arrow_button(int direction, Rectangle area) { const bool pressed=button_frame(area); const float offset=pressed?1:0; const Vector2 center{area.x+area.width/2+offset,area.y+area.height/2+offset}; const float tip=8,base=5; Vector2 first,second,third; if(direction==0){first={center.x,center.y-tip};second={center.x-base,center.y+base};third={center.x+base,center.y+base};} else if(direction==1){first={center.x-tip,center.y};second={center.x+base,center.y-base};third={center.x+base,center.y+base};} else if(direction==2){first={center.x+tip,center.y};second={center.x-base,center.y-base};third={center.x-base,center.y+base};} else {first={center.x,center.y+tip};second={center.x-base,center.y-base};third={center.x+base,center.y-base};} DrawTriangle(first,second,third,RED); DrawTriangleLines(first,second,third,BLACK); return pressed&&IsMouseButtonPressed(MOUSE_BUTTON_LEFT); }
  bool icon_button(int icon, Rectangle area) { const bool pressed=button_frame(area); const int offset=pressed?1:0; if(icon==0){DrawRectangle(static_cast<int>(area.x+4)+offset,static_cast<int>(area.y+9)+offset,13,7,GOLD);DrawRectangle(static_cast<int>(area.x+5)+offset,static_cast<int>(area.y+6)+offset,7,4,GOLD);DrawRectangleLines(static_cast<int>(area.x+4)+offset,static_cast<int>(area.y+9)+offset,13,7,BLACK);} else {DrawRectangle(static_cast<int>(area.x+5)+offset,static_cast<int>(area.y+4)+offset,12,13,Color{30,30,30,255});DrawRectangle(static_cast<int>(area.x+7)+offset,static_cast<int>(area.y+5)+offset,7,4,SKYBLUE);DrawRectangle(static_cast<int>(area.x+7)+offset,static_cast<int>(area.y+12)+offset,7,4,RAYWHITE);} return pressed&&IsMouseButtonPressed(MOUSE_BUTTON_LEFT); }
  void check(const char* text, float x, float y, bool& value) { Rectangle area=box(x,y,13,13); DrawRectangleRec(area,RAYWHITE); DrawRectangleLinesEx(area,1,Color{80,80,80,255}); if(value){DrawLine(static_cast<int>(x+3),static_cast<int>(y+6),static_cast<int>(x+5),static_cast<int>(y+9),BLACK);DrawLine(static_cast<int>(x+5),static_cast<int>(y+9),static_cast<int>(x+10),static_cast<int>(y+3),BLACK);} DrawText(text,static_cast<int>(x+18),static_cast<int>(y),12,BLACK); if(CheckCollisionPointRec(ui_mouse_position(),box(x,y,150,16))&&IsMouseButtonPressed(MOUSE_BUTTON_LEFT)) value=!value; }
  void group_box(const char* text, Rectangle area) { DrawRectangleLinesEx(area,1,GRAY); const int width=MeasureText(text,12); DrawRectangle(static_cast<int>(area.x+7),static_cast<int>(area.y-5),width+6,11,Color{238,238,238,255}); DrawText(text,static_cast<int>(area.x+10),static_cast<int>(area.y-6),12,BLACK); }
  void field(int id,const char* label, float x, float y, const std::string& value, float input_width=64) { DrawText(label,static_cast<int>(x),static_cast<int>(y+4),12,BLACK); const Rectangle area=box(x+96,y,input_width,20); DrawRectangleRec(area,RAYWHITE); DrawRectangleLinesEx(area,1,state.active==id?BLACK:GRAY); const auto& text=state.active==id?state.input:value; if(state.active==id&&state.input_selected)DrawRectangle(static_cast<int>(area.x+2),static_cast<int>(area.y+2),static_cast<int>(area.width-5),static_cast<int>(area.height-4),Color{0,120,215,255}); DrawText(text.c_str(),static_cast<int>(x+99),static_cast<int>(y+4),12,state.active==id&&state.input_selected?RAYWHITE:BLACK); if(state.active==id&&!state.input_selected){const auto prefix=state.input.substr(0,state.input_cursor);const int caret=static_cast<int>(area.x+3)+MeasureText(prefix.c_str(),12);DrawLine(caret,static_cast<int>(area.y+3),caret,static_cast<int>(area.y+16),BLACK);} if(CheckCollisionPointRec(ui_mouse_position(),area)&&IsMouseButtonPressed(MOUSE_BUTTON_LEFT)){state.active=id;state.input=value;state.input_cursor=state.input.size();state.input_selected=true;if(id==0)state.random=false;} }
  std::string number(double value) { char result[32]; std::snprintf(result,sizeof(result),"%g",value); return result; }
  void spin_field(int id,const char* label,float x,float y,double& value,double step) { DrawText(label,static_cast<int>(x),static_cast<int>(y+4),12,BLACK); const Rectangle area=box(x+96,y,64,20),arrows=box(area.x+48,area.y,16,20); DrawRectangleRec(area,RAYWHITE); DrawRectangleLinesEx(area,1,state.active==id?BLACK:GRAY); DrawLine(static_cast<int>(arrows.x),static_cast<int>(arrows.y+10),static_cast<int>(arrows.x+16),static_cast<int>(arrows.y+10),GRAY); DrawTriangle(Vector2{arrows.x+8,arrows.y+3},Vector2{arrows.x+4,arrows.y+8},Vector2{arrows.x+12,arrows.y+8},BLACK); DrawTriangle(Vector2{arrows.x+4,arrows.y+12},Vector2{arrows.x+12,arrows.y+12},Vector2{arrows.x+8,arrows.y+17},BLACK); const auto text=state.active==id?state.input:number(value); DrawText(text.c_str(),static_cast<int>(area.x+3),static_cast<int>(area.y+4),12,BLACK); if(CheckCollisionPointRec(ui_mouse_position(),arrows)&&IsMouseButtonReleased(MOUSE_BUTTON_LEFT)){value+=ui_mouse_position().y<arrows.y+10?step:-step;state.active=-1;} else if(CheckCollisionPointRec(ui_mouse_position(),box(area.x,area.y,48,20))&&IsMouseButtonReleased(MOUSE_BUTTON_LEFT)){state.active=id;state.input=number(value);} }
  // Detail mode keeps nine evenly spaced samples from each 65x65 level, producing eight preview cells per map cell.
  void rebuild(bool generate=false) { if(generate) terrain::regenerate_terrain_map(state.document); const int width=state.document.width,height=state.document.height; state.detail_pixels.clear();state.detail_heights.clear();state.zoom_heights.clear();if(state.document.heightmap.size()!=static_cast<size_t>(width+1)*(height+1)||state.document.random_seeds.size()!=static_cast<size_t>(width)*height){state.pixels.clear();return;} state.pixels.assign(static_cast<size_t>(width)*height,{}); for(int y=0;y<height;++y) for(int x=0;x<width;++x) { const auto control=[&](int control_x,int control_y){return state.document.heightmap[control_y*(width+1)+control_x];}; state.pixels[y*width+x]=terrain::preview_color(control(x,y),control(x+1,y),control(x,y+1),control(x+1,y+1),false); } if(!state.details&&state.zoom==1)return; if(state.detail_level_x<0){state.detail_level_x=0;state.detail_level_y=0;} const int detail_width=width*8+1,detail_height=height*8+1; state.detail_heights.assign(static_cast<size_t>(detail_width)*detail_height,0); const std::array<double,81> empty{}; const auto borders=terrain::generate_map_borders(state.document.heightmap,width,height,state.document.map_seed,state.document.level_height,state.document.level_chaos); std::vector<double> level; for(int level_y=0;level_y<height;++level_y)for(int level_x=0;level_x<width;++level_x){const auto name=terrain::generated_level_name(state.document,level_x,level_y);const auto override=std::find_if(state.document.height_overrides.begin(),state.document.height_overrides.end(),[&](const auto& item){return item.level_name==name;});const auto& samples=override==state.document.height_overrides.end()?empty:override->samples;terrain::generate_level_terrain(borders,width,height,level_x,level_y,state.document.random_seeds[level_y*width+level_x],state.document.level_height,state.document.level_chaos,samples,override!=state.document.height_overrides.end(),level);for(int sample_y=0;sample_y<=8;++sample_y)for(int sample_x=0;sample_x<=8;++sample_x)state.detail_heights[(level_y*8+sample_y)*detail_width+level_x*8+sample_x]=level[(sample_y*8)*65+sample_x*8];if(level_x==state.detail_level_x&&level_y==state.detail_level_y)state.zoom_heights=level;} state.detail_pixels.assign(static_cast<size_t>(width*8)*(height*8),{});for(int y=0;y<height*8;++y)for(int x=0;x<width*8;++x)state.detail_pixels[y*(width*8)+x]=terrain::preview_color(state.detail_heights[y*detail_width+x],state.detail_heights[y*detail_width+x+1],state.detail_heights[(y+1)*detail_width+x],state.detail_heights[(y+1)*detail_width+x+1],true); }
  void rebuild_control(int control_x,int control_y) { const int width=state.document.width,height=state.document.height;const auto control=[&](int x,int y){return state.document.heightmap[y*(width+1)+x];};for(int y=(std::max)(0,control_y-1);y<=(std::min)(height-1,control_y);++y)for(int x=(std::max)(0,control_x-1);x<=(std::min)(width-1,control_x);++x)state.pixels[y*width+x]=terrain::preview_color(control(x,y),control(x+1,y),control(x,y+1),control(x+1,y+1),false);if(state.detail_heights.empty())return;const int first_x=(std::max)(0,control_x-1),last_x=(std::min)(width-1,control_x),first_y=(std::max)(0,control_y-1),last_y=(std::min)(height-1,control_y),detail_width=width*8+1,detail_pixel_width=width*8;const std::array<double,81> empty{};const auto borders=terrain::generate_map_borders(state.document.heightmap,width,height,state.document.map_seed,state.document.level_height,state.document.level_chaos);std::vector<double> level;for(int level_y=first_y;level_y<=last_y;++level_y)for(int level_x=first_x;level_x<=last_x;++level_x){const auto name=terrain::generated_level_name(state.document,level_x,level_y);const auto override=std::find_if(state.document.height_overrides.begin(),state.document.height_overrides.end(),[&](const auto& item){return item.level_name==name;});const auto& samples=override==state.document.height_overrides.end()?empty:override->samples;terrain::generate_level_terrain(borders,width,height,level_x,level_y,state.document.random_seeds[level_y*width+level_x],state.document.level_height,state.document.level_chaos,samples,override!=state.document.height_overrides.end(),level);for(int sample_y=0;sample_y<=8;++sample_y)for(int sample_x=0;sample_x<=8;++sample_x)state.detail_heights[(level_y*8+sample_y)*detail_width+level_x*8+sample_x]=level[(sample_y*8)*65+sample_x*8];if(level_x==state.detail_level_x&&level_y==state.detail_level_y)state.zoom_heights=level;}for(int y=first_y*8;y<(last_y+1)*8;++y)for(int x=first_x*8;x<(last_x+1)*8;++x)state.detail_pixels[y*detail_pixel_width+x]=terrain::preview_color(state.detail_heights[y*detail_width+x],state.detail_heights[y*detail_width+x+1],state.detail_heights[(y+1)*detail_width+x],state.detail_heights[(y+1)*detail_width+x+1],true); }
  void set_selected_vertex(double value) { if(state.selected_detail&&state.detail_level_x>=0){const auto name=terrain::generated_level_name(state.document,state.detail_level_x,state.detail_level_y);auto override=std::find_if(state.document.height_overrides.begin(),state.document.height_overrides.end(),[&](const auto& item){return item.level_name==name;});if(override==state.document.height_overrides.end()){terrain::TerrainLevelOverride item;item.level_name=name;for(int y=0;y<=8;++y)for(int x=0;x<=8;++x)item.samples[y*9+x]=state.zoom_heights[(y*8)*65+x*8];state.document.height_overrides.push_back(std::move(item));override=std::prev(state.document.height_overrides.end());}override->samples[state.detail_sample_y*9+state.detail_sample_x]=value;state.zoom_heights[(state.detail_sample_y*8)*65+state.detail_sample_x*8]=value;const int detail_width=state.document.width*8+1,global_x=state.detail_level_x*8+state.detail_sample_x,global_y=state.detail_level_y*8+state.detail_sample_y;state.detail_heights[global_y*detail_width+global_x]=value;for(int y=(std::max)(0,global_y-1);y<=(std::min)(state.document.height*8-1,global_y);++y)for(int x=(std::max)(0,global_x-1);x<=(std::min)(state.document.width*8-1,global_x);++x)state.detail_pixels[y*(state.document.width*8)+x]=terrain::preview_color(state.detail_heights[y*detail_width+x],state.detail_heights[y*detail_width+x+1],state.detail_heights[(y+1)*detail_width+x],state.detail_heights[(y+1)*detail_width+x+1],true);}else if(state.selected_x>=0){terrain::edit_control_height(state.document,state.selected_x,state.selected_y,value);rebuild_control(state.selected_x,state.selected_y);}state.vertex_height=value; }
  std::string current_map_path;
  void open_document() { const char* patterns[]{"*.gmap"}; const char* selected=tinyfd_openFileDialog("Open terrain map",current_map_path.empty()?nullptr:current_map_path.c_str(),1,patterns,"Graal map",0); if(!selected)return; std::ifstream input(selected,std::ios::binary); if(!input)return; state.document=terrain::parse_terrain_gmap(std::string{std::istreambuf_iterator<char>{input},{}}); current_map_path=selected; state.selected_x=state.selected_y=-1; state.vertex_height=0; rebuild(); }
  std::string generated_name_for_map(const std::filesystem::path& map_path) { int column_digits=1,column_capacity=26; while(column_capacity<state.document.width){++column_digits;column_capacity*=26;} std::string column(static_cast<std::size_t>(column_digits),'a'); for(int value=state.document.width-1,index=column_digits-1;value>0&&index>=0;--index){column[static_cast<std::size_t>(index)]=static_cast<char>('a'+value%26);value/=26;} return map_path.stem().string()+"_"+column+"-"+std::to_string(state.document.height)+".nw"; }
  void save_generated_levels(const std::filesystem::path& map_path) { const std::array<double,81> empty{}; for(int y=0;y<state.document.height;++y)for(int x=0;x<state.document.width;++x){const auto name=terrain::generated_level_name(state.document,x,y); if(name.empty())continue; const auto override=std::find_if(state.document.height_overrides.begin(),state.document.height_overrides.end(),[&](const auto& item){return item.level_name==name;}); std::ofstream output(map_path.parent_path()/name,std::ios::binary|std::ios::trunc); if(output)output<<terrain::serialize_terrain_level(override==state.document.height_overrides.end()?std::span<const double,81>{empty}:std::span<const double,81>{override->samples},override!=state.document.height_overrides.end());} }
  void save_document(bool choose_path) { const bool new_path=choose_path||current_map_path.empty(); const char* patterns[]{"*.gmap"}; const char* selected=new_path?tinyfd_saveFileDialog("Save terrain map",current_map_path.empty()?"terrain.gmap":current_map_path.c_str(),1,patterns,"Graal map"):current_map_path.c_str(); if(!selected)return; const std::filesystem::path map_path(selected); if(new_path)state.document.generated=generated_name_for_map(map_path); std::ofstream output(map_path,std::ios::binary|std::ios::trunc); if(!output)return; output<<terrain::serialize_terrain_gmap(state.document); output.close(); if(state.graal_levels)save_generated_levels(map_path); current_map_path=selected; }
  Rectangle active_input_area() { switch(state.active){case 0:return box(585,43,88,20);case 1:return box(601,116,64,20);case 2:return box(601,139,64,20);case 3:return box(601,171,64,20);case 4:return box(601,216,64,20);case 5:return box(601,239,64,20);case 6:return box(594,394,64,20);default:return {};} }
  void commit_input() { try { switch(state.active){case 0:{const auto seed=std::stoll(state.input);if(seed<std::numeric_limits<std::int32_t>::min()||seed>std::numeric_limits<std::int32_t>::max())throw std::out_of_range("seed");state.document.map_seed=static_cast<std::uint32_t>(static_cast<std::int32_t>(seed));state.random=false;break;}case 1:state.document.width=std::clamp(std::stoi(state.input),1,64);break;case 2:state.document.height=std::clamp(std::stoi(state.input),1,64);break;case 3:state.document.base_height=std::stod(state.input);break;case 4:state.document.map_height=std::stod(state.input);break;case 5:state.document.map_chaos=std::stod(state.input);break;case 6:set_selected_vertex(std::stod(state.input));break;} }catch(...){} state.active=-1;state.input_selected=false;state.input_cursor=0; }
}
int terrain_cli_main(int argument_count, char** arguments);
int terrain_self_test();
int main(int argument_count, char** arguments) {
  if (argument_count == 2 && std::string_view(arguments[1]) == "--self-test") return terrain_self_test();
  if (argument_count > 1) return terrain_cli_main(argument_count, arguments);
  InitWindow(window_width,window_height,"Terrain Generator");
#if defined(_WIN32)
  set_window_icon();
#endif
  const std::array<const char*,3> font_paths{"C:/Windows/Fonts/micross.ttf","/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf","/System/Library/Fonts/Supplemental/Arial.ttf"}; for(const auto path:font_paths) if(std::filesystem::exists(path)){ui_font=LoadFontEx(path,12,nullptr,0);break;} if(!ui_font.texture.id) ui_font=GetFontDefault(); SetTextureFilter(ui_font.texture,TEXTURE_FILTER_BILINEAR); SetTargetFPS(60);
  while(!WindowShouldClose()) { if(state.active>=0&&IsMouseButtonPressed(MOUSE_BUTTON_LEFT)&&!CheckCollisionPointRec(ui_mouse_position(),active_input_area()))commit_input(); if(state.active>=0){const bool control=IsKeyDown(KEY_LEFT_CONTROL)||IsKeyDown(KEY_RIGHT_CONTROL);const auto replace_selection=[&](){if(state.input_selected){state.input.clear();state.input_cursor=0;state.input_selected=false;}};const auto insert=[&](char value){replace_selection();state.input.insert(state.input.begin()+static_cast<std::ptrdiff_t>(state.input_cursor),value);++state.input_cursor;};if(control&&IsKeyPressed(KEY_A)){state.input_selected=true;state.input_cursor=state.input.size();}if(control&&IsKeyPressed(KEY_C)&&state.input_selected)SetClipboardText(state.input.c_str());if(control&&IsKeyPressed(KEY_V)){const char* clipboard=GetClipboardText();replace_selection();if(clipboard)for(const char* value=clipboard;*value;++value)if((*value>='0'&&*value<='9')||*value=='.'||*value=='-')insert(*value);}bool received=false;int key;while((key=GetCharPressed())>0)if((key>='0'&&key<='9')||key=='.'||key=='-'){insert(static_cast<char>(key));received=true;}if(!received)for(int digit=0;digit<=9;++digit)if(IsKeyPressed(KEY_ZERO+digit))insert(static_cast<char>('0'+digit));if(IsKeyPressed(KEY_BACKSPACE)){if(state.input_selected)replace_selection();else if(state.input_cursor>0){state.input.erase(--state.input_cursor,1);}}if(IsKeyPressed(KEY_DELETE)){if(state.input_selected)replace_selection();else if(state.input_cursor<state.input.size())state.input.erase(state.input_cursor,1);}if(IsKeyPressed(KEY_LEFT)){state.input_selected=false;if(state.input_cursor>0)--state.input_cursor;}if(IsKeyPressed(KEY_RIGHT)){state.input_selected=false;if(state.input_cursor<state.input.size())++state.input_cursor;}if(IsKeyPressed(KEY_HOME)){state.input_selected=false;state.input_cursor=0;}if(IsKeyPressed(KEY_END)){state.input_selected=false;state.input_cursor=state.input.size();}if(IsKeyPressed(KEY_ENTER))commit_input();} BeginDrawing(); ClearBackground(RAYWHITE); BeginMode2D(Camera2D{{0,0},{static_cast<float>(frame_width),static_cast<float>(titlebar_height)},0,1}); DrawRectangle(panel_x,titlebar_height,GetScreenWidth()-panel_x+frame_width,GetScreenHeight(),Color{238,238,238,255}); DrawText("Random Seed:",498,49,12,BLACK); field(0,"",489,43,std::to_string(state.document.map_seed),88); check("random",585,68,state.random);
    group_box("Generator Options",box(489,100,191,218)); field(1,"Grid width:",505,116,std::to_string(state.document.width)); field(2,"Grid height:",505,139,std::to_string(state.document.height)); spin_field(3,"Base:",505,171,state.document.base_height,1); check("Even borders",505,197,state.document.even_borders); field(4,"Height:",505,216,number(state.document.map_height)); field(5,"Chaos:",505,239,number(state.document.map_chaos)); DrawText("Presets:",505,270,12,BLACK); if(button("Standard",box(569,264,99,23))){state.document.base_height=0;state.document.even_borders=false;state.document.map_height=65;state.document.map_chaos=.6;} if(button("Islands",box(569,288,99,23))){state.document.base_height=-32;state.document.even_borders=true;}
    if(button("Generate World",box(521,328,131,23))){if(state.active>=0)commit_input();if(state.random) state.document.map_seed=static_cast<uint32_t>(std::chrono::high_resolution_clock::now().time_since_epoch().count()); rebuild(true);} check("Show grid",498,361,state.grid); const bool was_details=state.details; check("Show level details",498,378,state.details); if(was_details!=state.details)rebuild(); const double previous_vertex_height=state.vertex_height; spin_field(6,"Vertex height:",498,394,state.vertex_height,1); if((state.selected_x>=0||state.selected_detail)&&state.vertex_height!=previous_vertex_height)set_selected_vertex(state.vertex_height); if(state.detail_level_x>=0){if(button("Zoom in/out",box(498,426,88,24))){state.zoom=state.zoom==1?2:1;rebuild();}}else disabled_button("Zoom in/out",box(498,426,88,24)); DrawText("Move zoom:",604,431,12,BLACK); if(arrow_button(0,box(622,445,22,22))&&state.zoom>1)state.zoom_y=(std::max)(0,state.zoom_y-1); if(arrow_button(1,box(599,461,22,22))&&state.zoom>1)state.zoom_x=(std::max)(0,state.zoom_x-1); if(arrow_button(2,box(645,461,22,22))&&state.zoom>1)state.zoom_x=(std::min)((std::max)(0,state.document.width-4),state.zoom_x+1); if(arrow_button(3,box(622,477,22,18))&&state.zoom>1)state.zoom_y=(std::min)((std::max)(0,state.document.height-4),state.zoom_y+1); if(icon_button(0,box(506,472,21,21)))open_document(); if(icon_button(1,box(531,472,21,21)))save_document(false); if(icon_button(1,box(555,472,21,21)))save_document(true); group_box("Save Options",box(489,503,191,40)); check("Generate Graal levels",505,519,state.graal_levels);
    if(!state.pixels.empty()&&CheckCollisionPointRec(ui_mouse_position(),box(terrain_left,terrain_top,terrain_width,terrain_height)) && IsMouseButtonPressed(MOUSE_BUTTON_LEFT)) { const auto mouse=ui_mouse_position(); if(state.zoom>1&&!state.detail_heights.empty()){const int origin_x=state.zoom_x,origin_y=state.zoom_y,visible_width=4,visible_height=4,detail_width=state.document.width*8+1;const float scale_x=static_cast<float>(terrain_width)/(visible_width*8),scale_y=static_cast<float>(terrain_height)/(visible_height*8),height_divisor=3.0f;float best=1e30f;int best_x=origin_x*8,best_y=origin_y*8;for(int y=origin_y*8;y<=static_cast<int>((origin_y+visible_height)*8);++y)for(int x=origin_x*8;x<=static_cast<int>((origin_x+visible_width)*8);++x){const Vector2 point{terrain_left+(x-origin_x*8)*scale_x,terrain_top+(y-origin_y*8)*scale_y-static_cast<float>(state.detail_heights[y*detail_width+x])/height_divisor};const float distance=Vector2DistanceSqr(mouse,point);if(distance<best){best=distance;best_x=x;best_y=y;}}state.detail_level_x=(std::min)(best_x/8,state.document.width-1);state.detail_level_y=(std::min)(best_y/8,state.document.height-1);state.detail_sample_x=best_x-state.detail_level_x*8;state.detail_sample_y=best_y-state.detail_level_y*8;state.vertex_height=state.detail_heights[best_y*detail_width+best_x];state.selected_detail=true;state.selected_x=state.selected_y=-1;rebuild();}else{const float scale_x=static_cast<float>(terrain_width)/state.document.width,scale_y=static_cast<float>(terrain_height)/state.document.height;float best=1e30f;for(int y=0;y<=state.document.height;++y)for(int x=0;x<=state.document.width;++x){const Vector2 point{terrain_left+x*scale_x,terrain_top+y*scale_y-static_cast<float>(state.document.heightmap[y*(state.document.width+1)+x])/3.0f};const float distance=Vector2DistanceSqr(mouse,point);if(distance<best){best=distance;state.drag_x=x;state.drag_y=y;}}state.detail_level_x=(std::clamp)(state.drag_x,0,state.document.width-1);state.detail_level_y=(std::clamp)(state.drag_y,0,state.document.height-1);state.zoom_x=(std::clamp)(state.detail_level_x-2,0,(std::max)(0,state.document.width-4));state.zoom_y=(std::clamp)(state.detail_level_y-2,0,(std::max)(0,state.document.height-4));state.selected_x=state.drag_x;state.selected_y=state.drag_y;state.selected_detail=false;state.vertex_height=state.document.heightmap[state.drag_y*(state.document.width+1)+state.drag_x];} state.drag_mouse_y=GetMouseY(); state.dragging=true; }
    if(state.dragging && IsMouseButtonDown(MOUSE_BUTTON_LEFT)) { const int delta=state.drag_mouse_y-GetMouseY(); if(delta){set_selected_vertex(state.vertex_height+delta*3.0);state.drag_mouse_y=GetMouseY();} }
    if(IsMouseButtonReleased(MOUSE_BUTTON_LEFT)) state.dragging=false;
    if(!state.pixels.empty()){const int pw=state.document.width,ph=state.document.height;const float scale_x=static_cast<float>(terrain_width)/pw,scale_y=static_cast<float>(terrain_height)/ph;const auto point=[&](int x,int y){return Vector2{terrain_left+x*scale_x,terrain_top+y*scale_y-static_cast<float>(state.document.heightmap[y*(pw+1)+x])/3.0f};};BeginScissorMode(0,0,panel_x-frame_width,window_height);if((state.details||state.zoom>1)&&!state.detail_heights.empty()){const int origin_x=state.zoom>1?state.zoom_x:0,origin_y=state.zoom>1?state.zoom_y:0,visible_width=state.zoom>1?4:pw,visible_height=state.zoom>1?4:ph,detail_width=pw*8+1,detail_pixel_width=pw*8;const float detail_scale_x=static_cast<float>(terrain_width)/(visible_width*8),detail_scale_y=static_cast<float>(terrain_height)/(visible_height*8),height_divisor=3.0f;const auto detail_point=[&](int x,int y){return Vector2{terrain_left+(x-origin_x*8)*detail_scale_x,terrain_top+(y-origin_y*8)*detail_scale_y-static_cast<float>(state.detail_heights[y*detail_width+x])/height_divisor};};for(int y=origin_y*8;y<(origin_y+visible_height)*8;++y)for(int x=origin_x*8;x<(origin_x+visible_width)*8;++x){const auto c=state.detail_pixels[y*detail_pixel_width+x];const auto tl=detail_point(x,y),tr=detail_point(x+1,y),bl=detail_point(x,y+1),br=detail_point(x+1,y+1);DrawTriangle(tl,bl,br,Color{c.red,c.green,c.blue,255});DrawTriangle(tl,br,tr,Color{c.red,c.green,c.blue,255});if(state.grid&&state.zoom>1){DrawLineV(tl,tr,Color{128,0,0,255});DrawLineV(tl,bl,Color{128,0,0,255});DrawLineV(bl,br,Color{128,0,0,255});DrawLineV(tr,br,Color{128,0,0,255});}if(state.grid&&x%8==0)DrawLineV(tl,bl,BLACK);if(state.grid&&y%8==0)DrawLineV(tl,tr,BLACK);if(state.grid&&x+1==(origin_x+visible_width)*8)DrawLineV(tr,br,BLACK);if(state.grid&&y+1==(origin_y+visible_height)*8)DrawLineV(bl,br,BLACK);}}else for(int y=0;y<ph;++y)for(int x=0;x<pw;++x){const auto c=state.pixels[y*pw+x];const auto tl=point(x,y),tr=point(x+1,y),bl=point(x,y+1),br=point(x+1,y+1);DrawTriangle(tl,bl,br,Color{c.red,c.green,c.blue,255});DrawTriangle(tl,br,tr,Color{c.red,c.green,c.blue,255});if(state.grid){DrawLineV(tl,tr,BLACK);DrawLineV(tl,bl,BLACK);DrawLineV(bl,br,BLACK);DrawLineV(tr,br,BLACK);}}EndScissorMode();}
    EndMode2D(); EndDrawing(); } CloseWindow(); }
